# Generated by Django 3.0.7 on 2020-06-22 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Predictions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField()),
                ('sym_name', models.CharField(max_length=10)),
                ('prediction', models.FloatField()),
            ],
        ),
    ]
