# Generated by Django 3.0.7 on 2020-06-22 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='predictions',
            old_name='prediction',
            new_name='sym_prediction',
        ),
        migrations.AlterField(
            model_name='predictions',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
