# Generated by Django 3.0.8 on 2020-07-02 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sentimentor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('general_sentiment', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Tickersentiment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('sym_name', models.CharField(max_length=12)),
                ('sentiment', models.CharField(max_length=15)),
            ],
        ),
    ]
